---
- name: Playbook to Configure vsftpd
  hosts: ftp
  become: true
  gather_facts: yes
  vars:
    - my_ftp_name: vsftpd
    - my_ftp_port: 21
  tasks:
    - name: Install "{{ my_ftp_name }}" package
      yum:
        name: "{{ my_ftp_name }}"
        state: present

    - name: Open firewall "{{ my_ftp_port }}"
      firewalld:
        immediate: yes
        permanent: yes
        state: enabled
        port: "{{ my_ftp_port }}/tcp"

    - name: Enable "{{ my_ftp_name }}" service
      service:
        name: "{{ my_ftp_name }}"
        state: started
        enabled: yes

    - name: Create a file on the FTP server
      copy:
        dest: /var/ftp/pub/readme.txt
        content: "This is {{ ansible_fqdn}}\n"
        owner: root
        group: root
        mode: "0644"
        setype: public_content_rw_t

    - name: Check FTP port "{{ my_ftp_port }}"
      ignore_errors: yes
      wait_for:
        host: "{{ ansible_fqdn }}"
        port: "{{ my_ftp_port }}"
        timeout: 2
...
